name: CI/CD for Regiao API

on:
  push:
    branches:
      - main  # Ou a branch principal do seu projeto
  pull_request:
    branches:
      - main  # Para rodar os testes também em pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Check-out do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configuração do .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Ajuste para a versão do .NET usada no seu projeto

    # 3. Restaurar dependências
    - name: Restore dependencies
      run: dotnet restore FIAP.APIRegiao.sln

    # 4. Build do projeto principal
    - name: Build project
      run: dotnet build FIAP.APIRegiao.sln --configuration Release --no-restore

    # 5. Executar testes do projeto APIRegioes.Testes
    - name: Run tests
      run: dotnet test APIRegioes.Testes/APIRegioes.Testes.csproj --configuration Release --no-build --logger "trx"

    # 6. Publicar a API (caso necessário)
    - name: Publish API project
      run: dotnet publish FIAP.APIRegiao/FIAP.APIRegiao.csproj --configuration Release --output ./publish

    # 7. Opcional: Implantação (deploy)
    - name: Deploy API
      run: |
        echo "Deploying application..."
        # Comandos adicionais de deploy podem ser colocados aqui
